[tool.poetry]
name = "electronic_archive"
version = "0.1.0"
description = ""
authors = ["Alexandr Monastyrtesky <alex.mon1989@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6"
requests = "^2.27.1"
pyodbc = "^4.0.32"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
get_docs = "electronic_archive.main:main"
